### ISSUE TITLE
(1) [Shipment] UI changes for Shipment Service Integration

### ISSUE THREAD

**Issue by creamdory** [elexess/erp-shipment#34]
### Ratings:

Effort: **Low**
Complexity: **Low**
Unknown: **Low**

### Task

- [x] Add a button "Fetch Shipping Provider Price"
- [x] Once button is clicked, it will show a pop-up dialog that will list all available prices and from which provider it is fetched. It will be listed as radio buttons for choosing. In the dialog, there is a button called "Create Shipment" that is activated once user selected a shipping cost line. Once this button is clicked, it will request an API call to create shipping record to the service provider.
- [x]  Add section for "Shipping Service Provider" with the following information. Will be auto populated once Shipment request is created.
- Shipping Server Provider (linked to provider)
- Reference Code
- Price
